version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_NAME=fastapi-learn
      - DB_USERNAME=postgres
      - SECRET_KEY=51ab4402d0b2040f812936a4355b06b8d75b25055ebd369186a6546d2e923841
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi-learn

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
