name: Build and Deploy

on:
  push:
    branches: 
      - main
      - feature branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repo
        uses: actions/checkout@v3
      - name: Say hi
        run: echo "hi, bro - it is awesome.."
