name: Build and Deploy

on:
  push:
    branches: 
      - main
      - feature branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repo
        uses: actions/checkout@v3
      - name: Setup python-3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install requirements.txt
        run: pip install -r requirements.txt
